from ctypes import *

from comtypes import COMObject
from comtypes.hresult import *

__all__ = ["ConnectableObjectMixin"]

class ConnectionPointImpl(COMObject):
    def __init__(self, sink_interface, sink_typeinfo) -> None: ...
    def IConnectionPoint_Advise(self, this, pUnk, pdwCookie): ...
    def IConnectionPoint_Unadvise(self, this, dwCookie): ...
    def IConnectionPoint_GetConnectionPointContainer(self, this, ppCPC): ...
    def IConnectionPoint_GetConnectionInterface(self, this, pIID): ...

class ConnectableObjectMixin:
    def __init__(self) -> None: ...
    def IConnectionPointContainer_EnumConnectionPoints(self, this, ppEnum): ...
    def IConnectionPointContainer_FindConnectionPoint(self, this, refiid, ppcp): ...
    def Fire_Event(self, itf, name, *args, **kw): ...
