from _typeshed import Incomplete
from comtypes import GUID as GUID, COMObject as COMObject
from comtypes.hresult import *
from comtypes.server import IClassFactory as IClassFactory

logger: Incomplete

class ClassFactory(COMObject):
    def __init__(self, cls) -> None: ...
    def IClassFactory_CreateInstance(self, this, punkOuter, riid, ppv): ...
    def IClassFactory_LockServer(self, this, fLock): ...

def inproc_find_class(clsid): ...
def DllGetClassObject(rclsid, riid, ppv): ...
def DllCanUnloadNow(): ...
