from _typeshed import Incomplete
from comtypes.hresult import *
from comtypes.server import w_getopt as w_getopt
from comtypes.typeinfo import (
    REGKIND_REGISTER as REGKIND_REGISTER,
    LoadTypeLibEx as LoadTypeLibEx,
    UnRegisterTypeLib as UnRegisterTypeLib,
)

def get_winerror(exception): ...

SHDeleteKey: Incomplete
Set = set

class Registrar:
    def nodebug(self, cls) -> None: ...
    def debug(self, cls, levels, format) -> None: ...
    def register(self, cls, executable: Incomplete | None = None) -> None: ...
    def unregister(self, cls, force: bool = False) -> None: ...

def register(cls) -> None: ...
def unregister(cls) -> None: ...
def UseCommandLine(*classes): ...
