from ctypes import *

__all__ = ["GUID"]

BYTE = c_byte
WORD = c_ushort
DWORD = c_ulong

class GUID(Structure):
    def __init__(self, name: str | GUID | None = None) -> None: ...
    def __unicode__(self): ...
    def copy(self): ...
    @classmethod
    def from_progid(cls, progid): ...
    def as_progid(self): ...
    @classmethod
    def create_new(cls): ...
