from ctypes import *

from _typeshed import Incomplete

__all__ = ["GUID"]

BYTE = c_byte
WORD = c_ushort
DWORD = c_ulong

class GUID(Structure):
    def __init__(self, name: Incomplete | None = None) -> None: ...
    def __unicode__(self): ...
    def __cmp__(self, other): ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def copy(self): ...
    @classmethod
    def from_progid(cls, progid): ...
    def as_progid(self): ...
    @classmethod
    def create_new(cls): ...
