S_OK: int
S_FALSE: int
E_UNEXPECTED: int
E_NOTIMPL: int
E_NOINTERFACE: int
E_POINTER: int
E_FAIL: int
E_INVALIDARG: int
E_OUTOFMEMORY: int
CLASS_E_NOAGGREGATION: int
CLASS_E_CLASSNOTAVAILABLE: int
CO_E_CLASSSTRING: int
CONNECT_E_CANNOTCONNECT: int
CONNECT_E_ADVISELIMIT: int
CONNECT_E_NOCONNECTION: int
TYPE_E_ELEMENTNOTFOUND: int
TYPE_E_REGISTRYACCESS: int
TYPE_E_CANTLOADLIBRARY: int
DISP_E_BUFFERTOOSMALL: int
DISP_E_DIVBYZERO: int
DISP_E_NOTACOLLECTION: int
DISP_E_BADCALLEE: int
DISP_E_PARAMNOTOPTIONAL: int
DISP_E_BADPARAMCOUNT: int
DISP_E_ARRAYISLOCKED: int
DISP_E_UNKNOWNLCID: int
DISP_E_BADINDEX: int
DISP_E_OVERFLOW: int
DISP_E_EXCEPTION: int
DISP_E_BADVARTYPE: int
DISP_E_NONAMEDARGS: int
DISP_E_UNKNOWNNAME: int
DISP_E_TYPEMISMATCH: int
DISP_E_PARAMNOTFOUND: int
DISP_E_MEMBERNOTFOUND: int
DISP_E_UNKNOWNINTERFACE: int
RPC_E_CHANGED_MODE: int
RPC_E_SERVERFAULT: int

def MAKE_HRESULT(sev, fac, code): ...

SEVERITY_ERROR: int
SEVERITY_SUCCESS: int
FACILITY_ITF: int
FACILITY_WIN32: int

def HRESULT_FROM_WIN32(x): ...
