from _typeshed import Incomplete

__all__ = ["insert_filter", "remove_filter", "run"]

class _MessageLoop:
    def __init__(self) -> None: ...
    def insert_filter(self, obj, index: int = -1) -> None: ...
    def remove_filter(self, obj) -> None: ...
    def run(self) -> None: ...
    def filter_message(self, lpmsg): ...

run: Incomplete
insert_filter: Incomplete
remove_filter: Incomplete
