from _typeshed import Incomplete

class Patch:
    target: Incomplete
    def __init__(self, target) -> None: ...
    def __call__(self, patches) -> None: ...

def no_replace(f): ...

class ReferenceEmptyClass: ...
