# https://github.com/BesLogic/Beslogic-Ruff-Config/
extend = ".venv/Beslogic-Ruff-Config/ruff.toml"

[lint]
ignore = [
  # Not needed or wanted
  "EXE", # Windows-only lib, ignore on CI
  "CPY001", # missing-copyright-notice: Assume license from root
  "PD", # Not using Pandas
  "PLC0415", # import-outside-top-level # https://github.com/astral-sh/ruff/issues/12803
  "T201", # Using print as log and for benchmark

  # FIXME/TODO: I'd normally set them as temporarily warnings, but no warnings in Ruff yet:
  # https://github.com/astral-sh/ruff/issues/1256 & https://github.com/astral-sh/ruff/issues/1774):
  "RUF012", # mutable-class-default

  # Changing these would break backwards compatibility
  "FBT001",
  "FBT002",
  "N801",
]
extend-select = [
  "ANN", # flake-annotations # WE USE IT IN THIS LIB TO PREVENT MISSING ANNOTATIONS

  # Python 3.11 introduced "zero cost" exception handling
  # Good to watch for, but often unfixable
  "PERF203", # try-except-in-loop, # WE WANT IT IN THIS LIBRARY FOR PERFORMANCE ON OLDER PYTHON
]
typing-modules = ["d3dshot._compat"]
