from _typeshed import Incomplete

class _frozen_attr_dict(dict):  # type: ignore[type-arg]
    def __getattr__(self, name): ...
    def __setitem__(self, key, value): ...
    def __delitem__(self, name): ...
    def __ior__(self, other): ...
    def clear(self): ...
    def pop(self, key, default: Incomplete | None = None): ...
    def popitem(self, last: bool = True): ...
    def setdefault(self, key, default: Incomplete | None = None): ...

class Constants:
    consts: Incomplete
    enums: Incomplete
    alias: Incomplete
    tcomp: Incomplete
    def __init__(self, obj) -> None: ...
    def __getattr__(self, name): ...
