from _typeshed import Incomplete
from comtypes._comobject import _MethodFinder
from comtypes.client._generate import GetModule as GetModule

logger: Incomplete

class _AdviseConnection:
    cp: Incomplete
    cookie: Incomplete
    receiver: Incomplete
    def __init__(self, source, interface, receiver) -> None: ...
    def disconnect(self) -> None: ...
    def __del__(self) -> None: ...

def FindOutgoingInterface(source): ...
def find_single_connection_interface(source): ...
def report_errors(func): ...

class _SinkMethodFinder(_MethodFinder):
    sink: Incomplete
    def __init__(self, inst, sink) -> None: ...
    def find_method(self, fq_name, mthname): ...

def CreateEventReceiver(interface, handler): ...
def GetEvents(source, sink, interface: Incomplete | None = None): ...

class EventDumper:
    def __getattr__(self, name): ...

def ShowEvents(source, interface: Incomplete | None = None): ...
def PumpEvents(timeout): ...
