from _typeshed import Incomplete
from comtypes.automation import (
    DISPATCH_METHOD as DISPATCH_METHOD,
    DISPATCH_PROPERTYGET as DISPATCH_PROPERTYGET,
    DISPATCH_PROPERTYPUT as DISPATCH_PROPERTYPUT,
    DISPATCH_PROPERTYPUTREF as DISPATCH_PROPERTYPUTREF,
    DISPID_NEWENUM as DISPID_NEWENUM,
    DISPID_VALUE as DISPID_VALUE,
    IEnumVARIANT as IEnumVARIANT,
)
from comtypes.typeinfo import FUNC_DISPATCH as FUNC_DISPATCH, FUNC_PUREVIRTUAL as FUNC_PUREVIRTUAL

class FuncDesc:
    def __init__(self, **kw) -> None: ...

class NamedProperty:
    get: Incomplete
    put: Incomplete
    putref: Incomplete
    disp: Incomplete
    def __init__(self, disp, get, put, putref) -> None: ...
    def __getitem__(self, arg): ...
    def __call__(self, *args): ...
    def __setitem__(self, name, value) -> None: ...
    def __iter__(self): ...

class Dispatch:
    def __init__(self, comobj, tinfo) -> None: ...
    def QueryInterface(self, *args): ...
    def __cmp__(self, other): ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def __getattr__(self, name): ...
    def __setattr__(self, name, value) -> None: ...
    def __call__(self, *args): ...
    def __getitem__(self, arg): ...
    def __setitem__(self, name, value) -> None: ...
    def __iter__(self): ...
