# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: Checks
on:
  workflow_dispatch: #  Allows manual builds
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ruff:
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v4
      - name: Get Ruff version
        id: ruff_version
        run: |
          $Env:RUFF_VERSION=Select-String -path pyproject.toml -pattern 'ruff ?([=<>~]?= ?[\d\.]+)' | %{ $_.Matches[0].Groups[1].Value }
          echo $Env:RUFF_VERSION
          echo "RUFF_VERSION=$Env:RUFF_VERSION" >> $Env:GITHUB_OUTPUT
      - uses: astral-sh/ruff-action@v2
        with:
          version: ${{ steps.ruff_version.outputs.RUFF_VERSION }}
  mypy:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        # Our minimum numpy 1 supported and latest numpy 2
        numpy-version: ["numpy>=2"]
        # To save on workflow runtime, only test old numpy on extreme ends of Python version
        # This should at least ensure support for oldest combination
        # and let us know when newest numpy drops support for any Python version
        include:
          - python-version: "3.9"
            numpy-version: "numpy==1.25.*"
          - python-version: "3.14"
            numpy-version: "numpy==1.26.*" # Fixes distutils removal issue with setuptools
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
          python-version: ${{ matrix.python-version }}
      - name: Install the project
        run: uv pip install -r pyproject.toml ${{ matrix.numpy-version }} --all-extras --system
      - run: uv run mypy d3dshot/
  Pyright:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        # Our minimum numpy 1 supported and latest numpy 2
        numpy-version: ["numpy>=2"]
        # To save on workflow runtime, only test old numpy on extreme ends of Python version
        # This should at least ensure support for oldest combination
        # and let us know when newest numpy drops support for any Python version
        include:
          - python-version: "3.9"
            numpy-version: "numpy==1.25.*"
          - python-version: "3.14"
            numpy-version: "numpy==1.26.*" # Fixes distutils removal issue with setuptools
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
          python-version: ${{ matrix.python-version }}
      - name: Install the project
        run: uv pip install -r pyproject.toml ${{ matrix.numpy-version }} --all-extras --system
      - name: Analysing the code with Pyright
        uses: jakebailey/pyright-action@v2
        with:
          python-version: ${{ matrix.python-version }}
          version: PATH
          working-directory: d3dshot/
